name: ai_project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - pip:
    - mlflow==2.7.1
    - plotly==5.16.1
    - scikit-plot==0.3.7
    - black==23.7.0
    - flake8==6.0.0
    - pylint==2.17.5
    - sphinx==7.1.2
    - sphinx-rtd-theme==1.3.0
    - pytest==7.4.0
    - pytest-cov==4.1.0
    - python-dotenv==1.0.0
    - requests==2.31.0
    - tqdm==4.66.1
    - nvidia-ml-py3==7.352.0 